services:
  db:
    image: postgres:16
    container_name: ddd-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ddd_demo
      TZ: Europe/Istanbul
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ddd_demo"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata: {}